name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: epicorganizer-frontend/epic-organizer/epic-organizer/frontend/package-lock.json
    - name: Change to frontend directory
      run: cd epicorganizer-frontend/epic-organizer/epic-organizer/frontend
    - run: npm i
    - run: npm run build --if-present
